### ISSUE TITLE
Access violation using Visual Studio 2019 and HxD 2.5

### ISSUE THREAD

**Issue by RobLinux** [maelh/hxd-plugin-framework#1] opened 2021-02-15 22:26 UTC
crashing here :
        *FriendlyTypeName = Converter->GetFriendlyTypeName().c_str();
*FriendlyTypeName is null

**Comment by maelh** [comment] 2021-03-07 17:13
Thanks for your report. I suppose by crash you mean an access violation? What happens exactly, and what steps do you need to take to trigger the issue?
I tested it here with VS2017, and I cannot reproduce it.

I assume you are merely compiling the C++ example?
Do you get the issue only with VS2019 or also VS2017?

What translation of HxD are you using?

Please double check you download the official HxD 2.5 version from my website, since I released beta/development versions on my forum.

Try the portable:
https://mh-nexus.de/en/downloads.php?product=HxD20

**Comment by maelh** [comment] 2021-03-07 17:27
My hunch is that the newly compiled file was not copied to the Plugins directory, and instead remained in the C++ example folder. Since FriendlyTypeName was introduced later, and TypeName uses a similar logic/code and does not create an issue, I assume this is a version mismatch problem.

**Comment by maelh** [comment] 2021-03-09 21:26
Published a tag for HxD 2.5, so you can download the right plugin source code as a ZIP file. Built the 32 bit and 64 bit C++ plugins under VC++ 2017, and both worked fine when using x86-32 and x86-64 version of HxD, respectively.

I'll close this issue, until more info is available.

**Closed as completed by maelh** 2021-03-09 21:26 UTC
